# Generated by Django 5.2 on 2025-05-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pregacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pregacoes',
            new_name='Pregacao',
        ),
    ]
