# Generated by Django 5.2 on 2025-05-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artigos',
            new_name='Artigo',
        ),
    ]
